### PR TITLE
Benp/visualize build data

### PR DESCRIPTION
**Pull request by benpatterson**

### CODE REVIEW

**Comment by benpatterson** [comment]
This is v 0.1. Feedback tells me that the data needs different representation, including build counts. But I didn't want this to linger too long as I wanted to give this a look on AWS lambda.

#SpareCycles

@edx/testeng All that said...feedback is welcome & so are questions. Here's an example screenshot.

CC @efagin 

image

**Comment by edx-webhook** [comment]
Thanks for the pull request, @benpatterson! I've created [OSPR-2116](https://openedx.atlassian.net/browse/OSPR-2116) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/testeng-ci/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by edx-webhook** [comment]
Thanks for the pull request, @benpatterson! I've created [OSPR-2362](https://openedx.atlassian.net/browse/OSPR-2362) to keep track of it in JIRA. JIRA is a place for product owners to prioritize feature reviews by the engineering development teams.

Feel free to add as much of the following information to the ticket:
- supporting documentation
- edx-code email threads
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will still be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).



If you like, you can add yourself to the [AUTHORS](https://github.com/edx/testeng-ci/blob/master/AUTHORS)      file for this repo, though that isn't required.     Please see the [CONTRIBUTING](https://github.com/edx/edx-platform/blob/master/CONTRIBUTING.rst)     file for more information.

**Comment by benpatterson** [comment]
I did love this one; the data was super-useful to visualize. But indeed....buh-bye. Thx for keeping your repos nice n clean, team. ⭐️

**Comment by estute** [comment]
@benpatterson we do have plans to monitor/measure/understand this data in the future. Perhaps we will scavenge this PR. Unfortunately it falls in the "not at the moment" bucket.

**Comment by benpatterson** [comment]
OMG of course @estute. I was just taking a moment to say g'bye to it. End-result might be something totally different, or even native to Travis nowadays--or even nothing at all. Who knows? No hurt feelings over here...just taking a moment to remember good times. 💃

**Pull request closed without merging**
