### PR TITLE
Provide one code coverage number based on our list of packages.

### PR DESCRIPTION
**Pull request by benpatterson**

### CODE REVIEW

**Comment by benpatterson** [comment]
@estute @jzoldak 

Also @aleffert depending on when he removes `mobile_app`

**Comment by benpatterson** [comment]
Ha @aleffert I see https://github.com/edx/jenkins-job-dsl/pull/2 now.

**Comment by aleffert** [comment]
👍

**Comment by aleffert** [comment]
Will nuke it once I get that PR merged and I can update some docs

**Comment by estute** [comment]
👍

**Comment by jzoldak** [comment]
👍

**Pull request merged**
