### PR TITLE
ARCHBOM-1632: Clean up PR creator and github helper

### PR DESCRIPTION
**Pull request by timmc-edx**
Various fixes and cleanups -- see commits. (Intended to be merged rather than squashed.)

### CODE REVIEW

**Comment by timmc-edx** [comment]
Te tests are giving a mocking-related error that I'm not clear on how to fix.

**Comment by robrap** [comment]
@timmc-edx: I see the following on the failed test:
```
@patch('jenkins.pull_request_creator.PullRequestCreator.github_helper.create_pull_request', return_value=None)
```
The failing code and error are as follows:
```
        pr = self.github_helper.create_pull_request(
            self.repository,
            self.pr_title,
            self.pr_body,
            'master',
            self.branch,
            user_reviewers=user_reviewers,
            team_reviewers=team_reviewers
        )

        LOGGER.info("Created PR: https://github.com/{}/pull/{}".format(
>           self.repository.full_name, pr.number
        ))
E       AttributeError: 'NoneType' object has no attribute 'number'
```

The problem is that your Mock is returning None, then `pr` is set to None, and then `pr.number` is breaking.  Instead, you'll want something like:
```
@patch('jenkins.pull_request_creator.PullRequestCreator.github_helper.create_pull_request', return_value=Mock())
```

This might be all you need, or you may need to add `number` with a return value to `create_pr_mock` inside the test.

Let me know if this is enough to get going.  Good luck.

**Comment by timmc-edx** [comment]
I've tried a bunch of things and none of them worked. It's a little hard to explain _what_ I've tried since there's such a pile of `@patch` decorators there, but... I've tried changing the None to Mock() and adding `create_pr_mock.number = 5` and things like that, but no luck, same error each time. May need to pair on this.

**Comment by robrap** [comment]
@timmc-edx: Try something like:
```
create_pr_mock.return_value.number.return_value = 5
```
I think it will be some sort of combination like this.  Not sure if this is right.

**Comment by timmc-edx** [comment]
Turns out part of the problem was that I was in the wrong file of a pair of near-identical (and equally confusing) test files. Resolution was to remove `return_value=None`.

**Review by feanil — APPROVED** [review]

**Review by adzuci — APPROVED** [review]

**Pull request merged**
