### PR TITLE
Skip author/pr_id lookup if parameters aren't set and add debug logging ...

### PR DESCRIPTION
**Pull request by clytwynec**
...for this

@benpatterson

### CODE REVIEW

**Comment by clytwynec** [comment]
... @jzoldak too

**Comment by benpatterson** [comment]
@clytwynec looks good. Could you add a test or two for the if/else flavors?

**Comment by jzoldak** [comment]
:+1: (just needs the pep8 fix.)

**Comment by benpatterson** [comment]
ditto. :+1:

**Pull request merged**
