### PR TITLE
Regression test using the sandbox provisioned by ansible

### PR DESCRIPTION
**Pull request by jzoldak**

### CODE REVIEW

**Comment by benpatterson** [comment]
Oh. I guess we can't use http right now...

**Comment by jzoldak** [comment]
@benpatterson looks like we never closed the loop with this one.

**Comment by benpatterson** [comment]
Right. I didn't like skipping courseware. Perhaps we run the same task twice...once for dashboard (etc) and once for courseware?

**Comment by jzoldak** [comment]
@benpatterson As discussed, I entered [TE-1128](https://openedx.atlassian.net/browse/TE-1128) for re-enabling the profiling of the Performance Course so that we can merge this PR in.

**Comment by benpatterson** [comment]
Yes.... :+1: on this change.

**Pull request merged**
